# Generated by Django 4.0.3 on 2022-03-18 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.URLField(default='https://source.unsplash.com/900x900/?car'),
            preserve_default=False,
        ),
    ]
