# Generated by Django 4.0.3 on 2022-03-21 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background', '0006_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_reporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='background.product')),
            ],
        ),
    ]
