# Generated by Django 4.0.3 on 2022-03-16 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background', '0002_remove_product_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dealershipID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='background.dealership')),
                ('salespersonID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='background.employee')),
            ],
        ),
    ]
