# Generated by Django 4.0.3 on 2022-03-16 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_remove_product_email'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('quantity', models.IntegerField()),
                ('order_formID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.order_form')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='background.product')),
            ],
        ),
    ]
