# Generated by Django 3.1.2 on 2022-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20220327_0518'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_form',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
