# Generated by Django 4.0.3 on 2022-03-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('background', '0002_remove_product_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='warranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.TextField(max_length=200)),
                ('productBundle', models.BooleanField()),
                ('extendedW', models.BooleanField()),
                ('effectiveDate', models.DateField()),
                ('expiryDate', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='background.customer')),
                ('dealershipID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='background.dealership')),
            ],
        ),
    ]
