# Generated by Django 4.0.3 on 2022-03-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='effectiveDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='expiryDate',
            field=models.DateTimeField(),
        ),
    ]
