# Generated by Django 4.0.3 on 2022-03-16 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_warranty_effectivedate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=3000)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('province', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pn', 'Pending'), ('Ap', 'Approved'), ('Sb', 'Submitted'), ('Pd', 'Paid')], default='Pn', max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('warrantyID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.warranty')),
            ],
        ),
    ]
