# Generated by Django 4.0.3 on 2022-03-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0003_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=200)),
                ('make', models.CharField(max_length=200)),
                ('model', models.CharField(max_length=200)),
                ('year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('colour', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Sc', 'Scheduled'), ('Cm', 'Completed'), ('Ex', 'Expired')], default='Sc', max_length=2)),
                ('scheduledDate', models.DateTimeField()),
                ('claimID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspections.claim')),
            ],
        ),
    ]
