# Generated by Django 3.1.2 on 2022-03-31 18:52

from django.db import migrations, models
import django.utils.timezone
import inspections.models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0005_auto_20220323_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='scheduledTime',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inspection',
            name='scheduledDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='vin',
            field=models.CharField(max_length=200, validators=[inspections.models.validate_vin]),
        ),
    ]
