# Generated by Django 3.1.2 on 2022-04-02 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_auto_20220331_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-id']},
        ),
    ]
